# Generated by Django 3.0.1 on 2019-12-27 21:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0002_session'),
    ]

    operations = [
        migrations.RenameField(
            model_name='session',
            old_name='userID',
            new_name='account',
        ),
    ]
