# Generated by Django 3.0.1 on 2019-12-28 21:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0003_auto_20191227_2105'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='nickname',
            field=models.CharField(default='undefined', max_length=20),
            preserve_default=False,
        ),
    ]
