# Generated by Django 3.0.1 on 2019-12-28 21:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='accountinfo',
            name='nickname',
        ),
    ]
