# Generated by Django 3.0.1 on 2019-12-31 07:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_auto_20191231_0154'),
    ]

    operations = [
        migrations.AddField(
            model_name='accountinfo',
            name='BMI',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='accountinfo',
            name='height',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='accountinfo',
            name='weight',
            field=models.IntegerField(default=0),
        ),
    ]
