# Generated by Django 3.0.1 on 2020-01-02 03:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_auto_20191231_0746'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accountinfo',
            name='avatar',
            field=models.ImageField(upload_to='avatar/'),
        ),
    ]
