# Generated by Django 3.0.1 on 2020-01-04 04:52

from django.db import migrations, models
import home.models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_auto_20200102_0313'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accountinfo',
            name='avatar',
            field=models.ImageField(upload_to='avatar/', validators=[home.models.validate_image]),
        ),
    ]
