# Generated by Django 3.0.1 on 2020-01-04 05:42

from django.db import migrations, models
import home.validators


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_auto_20200104_0452'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accountinfo',
            name='avatar',
            field=models.ImageField(default='avatar/1.png', upload_to='avatar/', validators=[home.validators.validate_image]),
        ),
    ]
