# Generated by Django 3.0.1 on 2020-01-04 07:15

from django.db import migrations, models
import home.validators


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_auto_20200104_0542'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accountinfo',
            name='avatar',
            field=models.ImageField(default='default/32.png', upload_to='avatar/', validators=[home.validators.validate_image]),
        ),
    ]
